name: Build Master

on:
  push:
    branches:
      - master
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 18:00:00 UTC (Monday at 10:00:00 PST)
    - cron: '0 18 * * 1'

jobs:
  test:
    name: Test in python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      COVERAGE_PYTHON_VERSION: 3.7
      COVERAGE_OS: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade virtualenv tox tox-gh-actions
    - name: "Run tox targets for ${{ matrix.python-version }}"
      run: "python -m tox"
    - name: "Generate coverage report"
      if: env.COVERAGE_PYTHON_VERSION == matrix.python-version && env.COVERAGE_OS == matrix.os
      run: |
        python -m pip install --upgrade coverage
        python -m coverage xml
    - name: "Upload coverage to Codecov"
      if: env.COVERAGE_PYTHON_VERSION == matrix.python-version && env.COVERAGE_OS == matrix.os
      uses: "codecov/codecov-action@v1"
      with:
        fail_ci_if_error: true
